///////////////////////////////////////////////////////////
//  Banque.cs
//  Implementation of the Class Banque
//  Generated by Enterprise Architect
//  Created on:      06-juil.-2021 15:47:16
//  Original author: Stagiaire
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using metiers;
namespace metiers {
	private class Banque {

		public Compte mesComptes;
		private int nbComptes;

		public Banque(string _nom, string _ville)
        {
            this.nomBanque = _nom;
            this.villeBanque = _ville;
            this.nbComptes = 0;

		}

		~Banque(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="_nom"></param>
		/// <param name="_ville"></param>
		public Banque(string _nom, string _ville){

		}

		/// 
		/// <param name="_uneCompte"></param>
		private void AjouterCompte(Compte _uneCompte)
        {


		}

		/// 
		/// <param name="_num"></param>
		/// <param name="_nom"></param>
		/// <param name="_solde"></param>
		/// <param name="_decouvertAutorise"></param>
		public void AjouterCompte(long _num, string _nom, double _solde, double _decouvertAutorise){

		}

		public Compte mesComptes{
			get{
				return mesComptes;
			}
		}

		public int NbComptes{
			get{
				return nbComptes;
			}
			set{
				nbComptes = value;
			}
		}

	}//end Banque

}//end namespace metiers